### ISSUE TITLE
How to build docker image

### ISSUE THREAD

**Issue by rich-junwang** [Ablustrund/MLPSandbox#2]
Hi, thanks for the releasing. For docker image like this `mplsandbox-python-3.9.19-v1`, are we able to release the dockerfile? Or have a short writeup about how to create such image? Thanks!

**Comment by Shichun-Liu** [comment]
Hello,
We used the `docker commit` command to package the experimental environment into an image, and then used the `docker save` command to export the image as a tar file. We have preserved as many details of the experimental environment as possible. Thank you for your question!
